import { cx } from '@/src/utils'
import './globals.css'
import { Inter, Manrope } from 'next/font/google'
import Header from '@/src/components/Header'
import Footer from '../components/Footer'
import Subscribe from '../components/Subscribe'

const inter = Inter({ subsets: ['latin'], display:'swap', variable:'--font-in' })
const manrope = Manrope({ subsets: ['latin'], display:'swap', variable:'--font-mr' })

export const metadata = {
  title: 'Blogging Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cx(inter.variable, manrope.variable, "font-mr bg-light max-w-[1440px] px-10 mx-auto")}>
        <Header/>
        {children}
        <Subscribe/>
        <Footer/>
      </body>
    </html>
  )
}
